### ISSUE TITLE
Providing Fax number in payment request leads to an error

### ISSUE THREAD

**Issue by stephan-schuster** [ratepay/php-library#33]
when adding a contact fax number to the payment request as described in https://github.com/ratepay/php-sdk/blob/master/example.paymentRequest.invoice.php the request fails with an exception. This error appeared after upgrading to PHP 8.1 and occurs not with PHP-Version 7.2

**Reproduce**: Take the example from https://github.com/ratepay/php-sdk/blob/master/example.paymentRequest.invoice.php, uncomment the fax number in line 91 and send the request.

**Result**:
Exception message: get_class(): Argument #1 ($object) must be of type object, string given
File: vendor/ratepay/php-library/src/Model/Request/SubModel/AbstractModel.php
Line: 104

**Comment by rommelfreddy** [comment]
Hello @stephan-schuster 
i am sorry to hear that you have problems with integrating the SDK in your application. 

Unfortunately the example is not correct. 
The example should look like this.:
```php
$contentArr = [
    'Customer' => [
        'Contacts' => [
            'Email' => "alice@umbrella.tld",
            'Phone' => [
                'AreaCode' => '012',
                'DirectDial' => '012 3456789'
            ],
            'Fax' => [
                'AreaCode' => '030',
                'DirectDial' => '012 84546'
            ],
        ],
    ]
];
```
we will update the example in the future.

**Tip:** you can also use the objects in the SDK to build your content. 
Please have a look into the Showpare 6 Mmodule:
https://github.com/ratepay/shopware6-module/blob/4.2/src/Components/RatepayApi/Factory/CustomerFactory.php
If you use the objects, you have to use the request builder:
https://github.com/ratepay/shopware6-module/blob/4.2/src/Components/RatepayApi/Service/Request/AbstractRequest.php
